In [16]:
'''from Training.generator_memory import generator
import numpy as np
from SSM.hippo import hippo_legs, discretize_bilinear
from SSM.helpers import sigmoid, binary_cross_entropy
from SSM.model import SimpleSSM
'''



from generator_memory import generator 
import numpy as np
from hippo import hippo_legs, discretize_bilinear
from helpers import sigmoid, binary_cross_entropy
from model_2 import SimpleSSM

In [14]:
#data parameters


#set data parameters
n_sequence = 1
n_train = 10000
n_test = 1000
time_step = 10
#n_batch

gen = generator(n_sequence, time_step, n_train)

x_train, y_train = gen.seq()

print(x_train[0:10])




[[4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]]


In [15]:
xx = x_train[0].reshape(-1, 1)
xx.shape
yy = y_train[0].reshape(-1,1)
yy.shape

(12, 1)

In [12]:
model = SimpleSSM()
print(y_train[0])
print(model.A)
for j in range(1):
    epoch_loss = 0.0 
    for i in range(x_train.shape[0]):
        loss, grads = model.loss_and_grads(x_train[i].reshape(-1, 1), y_train[i].reshape(-1,1))
        model.step(grads)
        epoch_loss += loss
    print('average loss= ' + str(epoch_loss/x_train.shape[0]))


print(model.A)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]
[[ 3.33333333e-01 -3.37864825e-16 -2.06854932e-16  1.93156033e-16
   1.87791344e-16 -6.85528257e-17 -3.86372710e-16 -2.22044605e-16]
 [-5.77350269e-01  3.90787006e-16  5.04503856e-16  1.05718735e-16
   2.67272645e-16 -8.03897845e-17  1.12980771e-17  1.28197512e-16]
 [-1.49071198e-01 -7.74596669e-01 -2.00000000e-01 -2.27533311e-16
  -4.09067390e-16 -1.41847656e-16 -1.43129241e-16 -1.33226763e-16]
 [ 1.67305193e-17  2.40200534e-17 -7.88810638e-01 -3.33333333e-01
   3.96229364e-16  1.34769839e-16  9.70851077e-17  1.12597166e-16]
 [-2.63804601e-17 -2.11656391e-16  1.27775313e-01 -7.55928946e-01
  -4.28571429e-01 -4.14709948e-16 -2.86168861e-16 -1.93074441e-16]
 [ 8.08598545e-17  3.17475477e-16 -3.53152309e-02  2.08927724e-01
  -7.10705312e-01 -5.00000000e-01  3.94126643e-16  1.69343971e-16]
 [-3.40644103e-17 -2.20133851e-16  1.27972345e-02 -7.57094604e-02
   2.57539377e-01 -6.64347819e-01 -5.55555556e-01 -7.65942485e-17]
 [-2.32620866e-17  1.44674860e-

In [17]:
x_train[1], y_train[1], model.forward(x_train[1].reshape(-1, 1))

(array([8., 0., 0., 0., 0., 0., 0., 0., 0., 0., 9., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 8.]),
 (array([[-3.56004170e+05],
         [ 2.12445311e+08],
         [-1.26776630e+11],
         [ 7.56538893e+13],
         [-4.51464197e+16],
         [ 2.69411028e+19],
         [-1.60770893e+22],
         [ 9.59399480e+24],
         [-5.72521148e+27],
         [ 3.41651702e+30],
         [-2.03880478e+33],
         [ 1.21665571e+36]]),
  array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 5.96257791e+02,  5.96104310e+02,  5.96534959e+02,
           5.96660267e+02,  5.95979664e+02,  5.96563328e+02,
           5.97583224e+02,  5.96929954e+02],
         [-3.55233883e+05, -3.55835507e+05, -3.56179332e+05,
          -3.56194831e+05, -3.56199144e+05, -3.56158326e+05,
          -3.56165115e+05, -3.56088097e+05],
         [ 2.11985806e+08,  2.12344289e+08,  

In [18]:
sigmoid(model.forward(x_train[0].reshape(-1, 1))[0])

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.]])