In [5]:
from generator import generator
import numpy as np
from hippo import hippo_legs, discretize_bilinear
from helpers import sigmoid, binary_cross_entropy
from model import SimpleSSM

In [3]:
#data parameters


#set data parameters
n_sequence = 1
n_train = 10000
n_test = 1000
time_step = 10
#n_batch

gen = generator(n_sequence, time_step, n_train)

x_train, y_train = gen.seq()




In [16]:
xx = x_train[0].reshape(-1, 1)
xx.shape
yy = y_train[0].reshape(-1,1)
yy.shape

(12, 1)

In [26]:
model = SimpleSSM()


for i in range(x_train.shape[0]):
    loss, grads = model.loss_and_grads(x_train[i].reshape(-1, 1), y_train[i].reshape(-1,1))
    model.step(grads)



/Users/admin/Desktop/phy 329/ssm/helpers.py:4: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-x))


In [39]:
x_train[1], y_train[1], model.forward(x_train[1].reshape(-1, 1))

(array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 9., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 6.]),
 (array([[-2.72458503e+05],
         [ 1.64009600e+08],
         [-9.87247146e+10],
         [ 5.94268226e+13],
         [-3.57716632e+16],
         [ 2.15325645e+19],
         [-1.29614139e+22],
         [ 7.80205492e+24],
         [-4.69640591e+27],
         [ 2.82697683e+30],
         [-1.70168383e+33],
         [ 1.02431963e+36]]),
  array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [-4.47354230e+02, -4.51421344e+02, -4.46870009e+02,
          -4.52003003e+02, -4.51438948e+02, -4.49887591e+02,
           4.54681307e+02,  4.54563494e+02],
         [ 2.70922473e+05,  2.71448900e+05,  2.71615895e+05,
           2.71668531e+05,  2.71630086e+05,  2.71383195e+05,
          -2.71546469e+05, -2.71747088e+05],
         [-1.63079071e+08, -1.63397515e+08, -

In [38]:
sigmoid(model.forward(x_train[0].reshape(-1, 1))[0])

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.]])